"""Structural contract implemented independently by each broker adapter."""

from __future__ import annotations

from typing import Any, Awaitable, Callable, Protocol


class BrokerAdapter(Protocol):
    def MakeBroker(self, client: Any) -> Any: ...
    def CanStream(self, client: Any) -> bool: ...
    def IsMarketOpen(self, broker: Any) -> bool: ...
    def SubmitOrder(self, broker: Any, symbol: str, quantity: float, side: str) -> Any: ...
    def GetCash(self, broker: Any) -> Any: ...
    def GetPositions(self, broker: Any) -> list[Any]: ...
    def GetOpenOrders(self, broker: Any) -> list[Any]: ...
    def GetOrderKey(self, order: Any) -> str: ...
    def GetOrderStatus(self, order: Any) -> str: ...
    def GetUpdateEvent(self, update: Any) -> str: ...
    def GetUpdateOrder(self, update: Any) -> Any: ...
    def GetExecutionKey(self, update: Any) -> str: ...
    def ToVQCPosition(self, position: Any) -> Any: ...
    def ToVQCOrder(self, order: Any, order_id: int) -> Any: ...
    def ToVQCFill(self, update: Any, execution_id: int, order_id: int) -> Any: ...
    def RunTradeStream(self, client: Any, callback: Callable[[Any], Awaitable[None]]) -> None: ...


__all__ = ["BrokerAdapter"]
